<!-- 
Вывод массива $posts с массивами постов, одним словом - список постов, 
но с пейджингом: на каждой странице по 5 постов.
-->

<a href="<?= $urlMain ?>">На Главную</a>
<br><br>

<?php if ($page >= 1): ?>
    <?php foreach ($posts as $post): ?>
        <div>
            <a href="/posts/<?= $post['id'] ?>"><?= $post['name'] ?></a>
        </div>           
    <?php endforeach ?>
    <br>
    <!--<a href="/posts?page=<?= $page - 1 ?>&per=5">< Сюда</a>-->
    <!--<a href="/posts?page=<?= $page + 1 ?>&per=5">Туда ></a>-->
    <!-- END -->
    <!-- 
    Условия для отображения кнопок перелистывания пейджинга. Если мы на первой 
    или последней странице, то соответсвенно исчезают кнопки Назад и Вперёд.
    -->
    <?php if ($page > 1): ?>
        <a href="/posts?page=<?= $page - 1 ?>&per=5" style="<?= $style ?>" >< Назад</a>
    <?php endif; ?>    
    <?php if ($posts): ?>
        <a href="/posts?page=<?= $page + 1 ?>&per=5" style="<?= $style ?>">Вперёд ></a>
    <?php endif; ?>
<?php endif; ?>

<!-- 
Вариант кнопок с хекслет: гораздо короче, но ваще не понятно
-->  
<!--    <div>
        <a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>" style="<?= $style ?>">Prev</a> 
        <a href="?page=<?= $page + 1 ?>" style="<?= $style ?>">Next</a>
    </div>-->