<!-- 
Форма создания нового курса, которая отправляется через обработчик POST /courses на 
главную страницу в случае если она проходит проверку.
-->
<form action="<?= $url; ?>" method="post">
  <div>
    <label>
      Название
      <!--
      1)в атрибуте name значение заданно в виде асац.массива, и каждое значение его определяется, 
      как ключ в этом массиве. Т.е в него, в качестве значения этого ключа, подставляется то, 
      что ввёл пользователь.
      2)в атрибуте value идёт подстановка значений введённых пользователем, 
      это поможет реализовать проверку. Этот код ($course['title'] ?? '') подставит в атрибут 
      value либо введённые данные или пустоту), и либо то, либо другое отправить на сервер.
      * На сервер отправляется пара «имя=значение», где имя задается атрибутом
      name тега <input>, а значение — атрибутом value.
      -->
      <input type="text" name="course[title]" value="<?= htmlspecialchars($course['title'] ?? '') ?>">
    </label>
    <?php if (isset($errors['title'])): ?>
      <div><?= $errors['title'] ?></div>
    <?php endif ?>
  </div>
  <div>
      <label>
      Платный/Бесплатный
      <select name="course[paid]">
        <option value="">Select</option>
        <option <?= isset($course['paid']) && $course['paid'] ? 'selected' : '' ?> value="true">Платно</option>
        <option <?= isset($course['paid']) && $course['paid'] ? 'selected' : '' ?> value="false">Безплатно</option>
      </select>
    </label>
    <?php if (isset($errors['paid'])): ?>
      <div><?= $errors['paid'] ?></div>
    <?php endif ?>
  </div>
  <input type="submit" value="Sign Up">
</form>
