<a href="<?= $urlMain ?>">На Главную</a>

<h3>Таблица Пользователей</h3>

<?php if (count($messages) > 0): ?>
    <ul>
        <?php foreach ($messages as $message): ?>
            <?php foreach ($message as $messageFlash): ?>
                <li><?= $messageFlash ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

   <!-- /users/new -->
<a href="<?= $url ?>">Создать нового пользователя</a> или <a href="<?= $urlFind ?>">Найти по Имени</a>
<br><br>
<!--Список пользователей непосредственно-->
<table>
    <tr style="color: red">
        <td>ID</td>
        <td>firstName</td>      
    </tr>

    <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <?= $user['id'] ?>
            </td>
            <td>
                <!--короткий адрес-->
                <a href="/users/<?= htmlspecialchars($user['id']) ?>">
                    <?= htmlspecialchars($user['firstName']) ?>
                </a>
                <!--полный адрес, изначально он был. Не совсем понимаю, как короткий работает-->
                <!-- http://localhost:800/users/ -->
            </td>
        </tr>
    <?php endforeach ?>
</table>
<br>
<h3>Таблица Пользователей из cookie</h3>
<table>
    <tr style="color: red">
        <td>ID</td>
        <td>firstName</td>
        <td>lastName</td>
        <td>email</td>  
    </tr>
    <!--Инфа о пользователях появится только если куки заряжены))-->
    <?php if ($cart): ?>
        <?php foreach ($cart as $array): ?>
            <tr>
                <td>
                    <?= $array['id'] ?>
                </td>
                <td>
                    <?= $array['firstName'] ?>
                </td>
                <td>
                    <?= $array['lastName'] ?>
                </td>
                <td>
                    <?= $array['email'] ?>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>
